version: "3.7"

x-base: &base
    environment:
        - ENV=development
        - TZ=Europe/Athens
    networks:
        - acarsserver_net
    volumes:
        - ./:/acars-server

services:
    client:
        <<: *base
        build:
            context: ./
            dockerfile: docker/client/Dockerfile
            args:
                - ENV=development
        hostname: client
        devices:
            - "/dev/bus/usb:/dev/bus/usb"

    image_downloader:
        <<: *base
        build:
            context: ./
            dockerfile: docker/image_downloader/Dockerfile
            args:
                - ENV=development
        depends_on: [rabbitmq]
        hostname: image-downloader

    listener:
        <<: *base
        build:
            context: ./
            dockerfile: docker/listener/Dockerfile
            args:
                - ENV=development
        depends_on: [rabbitmq]
        hostname: listener
        ports:
            - target: 5555
              published: 5555
              protocol: udp

    web:
        <<: *base
        build:
            context: ./
            dockerfile: docker/web/Dockerfile
            args:
                - ENV=development
        hostname: web
        ports:
            - "8080:8080"

    rabbitmq:
        image: rabbitmq:3
        hostname: rabbitmq
        environment:
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
        networks:
            - acarsserver_net

    test:
        <<: *base
        environment:
            - ENV=test
            - TZ=Europe/Athens
        build:
            context: ./
            dockerfile: docker/test/Dockerfile
            args:
                - HOST_USER_NAME=mylk
                - HOST_USER_ID=1000
                - HOST_GROUP_ID=1000
        depends_on: [rabbitmq]
        hostname: test

networks:
    acarsserver_net:
        driver: "bridge"
